config_version = "0"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "checkov"
version = "3.2.49"

[[plugin]]
name = "markdownlint"
version = "0.31.1"

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "prettier"
version = "2.8.4"

[[plugin]]
name = "ripgrep"

[[plugin]]
name = "trivy"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"

[[triage]]
match.file_patterns = [".github/workflows/*"]
match.rules = ["yamllint:line-length"]
set.ignored = true

# Prettier normalizes inline comments to one leading space, which conflicts
# with yamllint's default two-space requirement
[[triage]]
match.file_patterns = [".github/workflows/*"]
match.rules = ["yamllint:comments"]
set.ignored = true