name: Main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    
permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Copy lcov.info to /tmp/coverage
        run: |
          mkdir -p /tmp/coverage
          cp coverage/lcov.info /tmp/coverage/lcov.info
      - uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: /tmp/coverage/lcov.info
